import { Element } from './types';

export const elements: Element[] = [
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicMass: 1.008,
    category: 'nonmetal',
    block: 's',
    group: 1,
    period: 1,
    electronConfiguration: '1s¹',
    electronegativity: 2.2,
    density: 0.00008988,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    discoveredBy: 'Henry Cavendish',
    yearDiscovered: 1766,
    description: 'Hydrogen is the lightest and most abundant element in the universe. It is a colorless, odorless, and highly flammable gas at room temperature.',
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    atomicMass: 4.002602,
    category: 'noble gas',
    block: 's',
    group: 18,
    period: 1,
    electronConfiguration: '1s²',
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    discoveredBy: 'Pierre Janssen',
    yearDiscovered: 1868,
    description: 'Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table.',
  },
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicMass: 6.94,
    category: 'alkali metal',
    block: 's',
    group: 1,
    period: 2,
    electronConfiguration: '[He] 2s¹',
    electronegativity: 0.98,
    density: 0.534,
    meltingPoint: 453.69,
    boilingPoint: 1615,
    discoveredBy: 'Johan August Arfwedson',
    yearDiscovered: 1817,
    description: 'Lithium is a soft, silvery-white alkali metal. It is the lightest metal and the lightest solid element under normal conditions.',
  },
  {
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicMass: 9.0121831,
    category: 'alkaline earth metal',
    block: 's',
    group: 2,
    period: 2,
    electronConfiguration: '[He] 2s²',
    electronegativity: 1.57,
    density: 1.85,
    meltingPoint: 1560,
    boilingPoint: 2742,
    discoveredBy: 'Louis Nicolas Vauquelin',
    yearDiscovered: 1797,
    description: 'Beryllium is a relatively rare element in the universe. It is a divalent element that occurs naturally only in combination with other elements in minerals.',
  },
  {
    number: 5,
    symbol: 'B',
    name: 'Boron',
    atomicMass: 10.81,
    category: 'metalloid',
    block: 'p',
    group: 13,
    period: 2,
    electronConfiguration: '[He] 2s² 2p¹',
    electronegativity: 2.04,
    density: 2.34,
    meltingPoint: 2349,
    boilingPoint: 4200,
    description: 'Boron is a chemical element with properties lying between metals and nonmetals.',
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicMass: 12.011,
    category: 'nonmetal',
    block: 'p',
    group: 14,
    period: 2,
    electronConfiguration: '[He] 2s² 2p²',
    electronegativity: 2.55,
    density: 2.267,
    meltingPoint: 3823,
    boilingPoint: 4300,
    description: 'Carbon is a nonmetallic element that is the basis of organic chemistry and life on Earth.',
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicMass: 14.007,
    category: 'nonmetal',
    block: 'p',
    group: 15,
    period: 2,
    electronConfiguration: '[He] 2s² 2p³',
    electronegativity: 3.04,
    density: 0.001251,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    description: 'Nitrogen is a colorless, odorless, and tasteless gas that makes up about 78% of Earth\'s atmosphere.',
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicMass: 15.999,
    category: 'nonmetal',
    block: 'p',
    group: 16,
    period: 2,
    electronConfiguration: '[He] 2s² 2p⁴',
    electronegativity: 3.44,
    density: 0.001429,
    meltingPoint: 54.36,
    boilingPoint: 90.20,
    description: 'Oxygen is a highly reactive nonmetal that is essential for most life forms on Earth.',
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicMass: 18.998403163,
    category: 'halogen',
    block: 'p',
    group: 17,
    period: 2,
    electronConfiguration: '[He] 2s² 2p⁵',
    electronegativity: 3.98,
    density: 0.001696,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    description: 'Fluorine is the most reactive and electronegative of all elements.',
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicMass: 20.1797,
    category: 'noble gas',
    block: 'p',
    group: 18,
    period: 2,
    electronConfiguration: '[He] 2s² 2p⁶',
    density: 0.0008999,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    description: 'Neon is a noble gas that glows reddish-orange in vacuum discharge tubes.',
  },
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicMass: 22.98976928,
    category: 'alkali metal',
    block: 's',
    group: 1,
    period: 3,
    electronConfiguration: '[Ne] 3s¹',
    electronegativity: 0.93,
    density: 0.971,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    description: 'Sodium is a soft, silvery-white, highly reactive metal.',
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicMass: 24.305,
    category: 'alkaline earth metal',
    block: 's',
    group: 2,
    period: 3,
    electronConfiguration: '[Ne] 3s²',
    electronegativity: 1.31,
    density: 1.738,
    meltingPoint: 923,
    boilingPoint: 1363,
    description: 'Magnesium is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.',
  },
  {
    number: 13,
    symbol: 'Al',
    name: 'Aluminum',
    atomicMass: 26.9815385,
    category: 'post-transition metal',
    block: 'p',
    group: 13,
    period: 3,
    electronConfiguration: '[Ne] 3s² 3p¹',
    electronegativity: 1.61,
    density: 2.70,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    description: 'Aluminum is a silvery-white, soft, nonmagnetic, ductile metal.',
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicMass: 28.085,
    category: 'metalloid',
    block: 'p',
    group: 14,
    period: 3,
    electronConfiguration: '[Ne] 3s² 3p²',
    electronegativity: 1.9,
    density: 2.329,
    meltingPoint: 1687,
    boilingPoint: 3538,
    description: 'Silicon is a hard and brittle crystalline solid with a blue-grey metallic lustre.',
  },
  {
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicMass: 30.973761998,
    category: 'nonmetal',
    block: 'p',
    group: 15,
    period: 3,
    electronConfiguration: '[Ne] 3s² 3p³',
    electronegativity: 2.19,
    density: 1.823,
    meltingPoint: 317.3,
    boilingPoint: 553.6,
    description: 'Phosphorus is a highly reactive nonmetal that glows in the dark.',
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicMass: 32.06,
    category: 'nonmetal',
    block: 'p',
    group: 16,
    period: 3,
    electronConfiguration: '[Ne] 3s² 3p⁴',
    electronegativity: 2.58,
    density: 2.067,
    meltingPoint: 388.36,
    boilingPoint: 717.87,
    description: 'Sulfur is a yellow nonmetallic element found in nature in large quantities.',
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicMass: 35.45,
    category: 'halogen',
    block: 'p',
    group: 17,
    period: 3,
    electronConfiguration: '[Ne] 3s² 3p⁵',
    electronegativity: 3.16,
    density: 0.003214,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    description: 'Chlorine is a yellow-green gas at room temperature.',
  },
  {
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicMass: 39.948,
    category: 'noble gas',
    block: 'p',
    group: 18,
    period: 3,
    electronConfiguration: '[Ne] 3s² 3p⁶',
    density: 0.0017837,
    meltingPoint: 83.80,
    boilingPoint: 87.30,
    description: 'Argon is the third most abundant gas in Earth\'s atmosphere.',
  },
  {
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicMass: 39.0983,
    category: 'alkali metal',
    block: 's',
    group: 1,
    period: 4,
    electronConfiguration: '[Ar] 4s¹',
    electronegativity: 0.82,
    density: 0.862,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    description: 'Potassium is a soft silvery-white alkali metal that oxidizes rapidly in air.',
  },
  {
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicMass: 40.078,
    category: 'alkaline earth metal',
    block: 's',
    group: 2,
    period: 4,
    electronConfiguration: '[Ar] 4s²',
    electronegativity: 1.00,
    density: 1.54,
    meltingPoint: 1115,
    boilingPoint: 1757,
    description: 'Calcium is a soft gray alkaline earth metal that is essential for living organisms.',
  },
  {
    number: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicMass: 44.955908,
    category: 'transition metal',
    block: 'd',
    group: 3,
    period: 4,
    electronConfiguration: '[Ar] 3d¹ 4s²',
    electronegativity: 1.36,
    density: 2.989,
    meltingPoint: 1814,
    boilingPoint: 3109,
    description: 'Scandium is a silvery-white metallic d-block element.',
  },
  {
    number: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicMass: 47.867,
    category: 'transition metal',
    block: 'd',
    group: 4,
    period: 4,
    electronConfiguration: '[Ar] 3d² 4s²',
    electronegativity: 1.54,
    density: 4.506,
    meltingPoint: 1941,
    boilingPoint: 3560,
    description: 'Titanium is a strong, lightweight metal used in aerospace and medical applications.',
  },
  {
    number: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicMass: 50.9415,
    category: 'transition metal',
    block: 'd',
    group: 5,
    period: 4,
    electronConfiguration: '[Ar] 3d³ 4s²',
    electronegativity: 1.63,
    density: 6.11,
    meltingPoint: 2183,
    boilingPoint: 3680,
    description: 'Vanadium is a hard, silvery-gray, ductile, and malleable transition metal.',
  },
  {
    number: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicMass: 51.9961,
    category: 'transition metal',
    block: 'd',
    group: 6,
    period: 4,
    electronConfiguration: '[Ar] 3d⁵ 4s¹',
    electronegativity: 1.66,
    density: 7.15,
    meltingPoint: 2180,
    boilingPoint: 2944,
    description: 'Chromium is a steely-grey, lustrous, hard metal that takes a high polish and has a high melting point.',
  },
  {
    number: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicMass: 54.938044,
    category: 'transition metal',
    block: 'd',
    group: 7,
    period: 4,
    electronConfiguration: '[Ar] 3d⁵ 4s²',
    electronegativity: 1.55,
    density: 7.21,
    meltingPoint: 1519,
    boilingPoint: 2334,
    description: 'Manganese is a silvery-gray metal that resembles iron and is hard and very brittle.',
  },
  {
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicMass: 55.845,
    category: 'transition metal',
    block: 'd',
    group: 8,
    period: 4,
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    electronegativity: 1.83,
    density: 7.874,
    meltingPoint: 1811,
    boilingPoint: 3134,
    description: 'Iron is the most widely used of all metals, forming much of Earth\'s outer and inner core.',
  },
  {
    number: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicMass: 58.933194,
    category: 'transition metal',
    block: 'd',
    group: 9,
    period: 4,
    electronConfiguration: '[Ar] 3d⁷ 4s²',
    electronegativity: 1.88,
    density: 8.90,
    meltingPoint: 1768,
    boilingPoint: 3200,
    description: 'Cobalt is a hard, lustrous, silver-blue metal used in magnetic alloys and blue colorants.',
  },
  {
    number: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicMass: 58.6934,
    category: 'transition metal',
    block: 'd',
    group: 10,
    period: 4,
    electronConfiguration: '[Ar] 3d⁸ 4s²',
    electronegativity: 1.91,
    density: 8.908,
    meltingPoint: 1728,
    boilingPoint: 3186,
    description: 'Nickel is a silvery-white metal with a slight golden tinge that takes a high polish.',
  },
  {
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicMass: 63.546,
    category: 'transition metal',
    block: 'd',
    group: 11,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    electronegativity: 1.90,
    density: 8.96,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    description: 'Copper is a ductile metal with very high thermal and electrical conductivity.',
  },
  {
    number: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicMass: 65.38,
    category: 'transition metal',
    block: 'd',
    group: 12,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s²',
    electronegativity: 1.65,
    density: 7.14,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    description: 'Zinc is a bluish-white, lustrous, diamagnetic metal that is brittle at room temperature.',
  },
  {
    number: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicMass: 69.723,
    category: 'post-transition metal',
    block: 'p',
    group: 13,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹',
    electronegativity: 1.81,
    density: 5.904,
    meltingPoint: 302.9146,
    boilingPoint: 2477,
    description: 'Gallium is a soft, silvery metal that melts at slightly above room temperature.',
  },
  {
    number: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicMass: 72.630,
    category: 'metalloid',
    block: 'p',
    group: 14,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²',
    electronegativity: 2.01,
    density: 5.323,
    meltingPoint: 1211.40,
    boilingPoint: 3106,
    description: 'Germanium is a lustrous, hard, grayish-white metalloid in the carbon group.',
  },
  {
    number: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicMass: 74.921595,
    category: 'metalloid',
    block: 'p',
    group: 15,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³',
    electronegativity: 2.18,
    density: 5.727,
    meltingPoint: 1090,
    boilingPoint: 887,
    description: 'Arsenic is a metalloid that can exist in several allotropic forms.',
  },
  {
    number: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicMass: 78.971,
    category: 'nonmetal',
    block: 'p',
    group: 16,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    electronegativity: 2.55,
    density: 4.809,
    meltingPoint: 494,
    boilingPoint: 958,
    description: 'Selenium is a nonmetal with properties intermediate between those of sulfur and tellurium.',
  },
  {
    number: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicMass: 79.904,
    category: 'halogen',
    block: 'p',
    group: 17,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    electronegativity: 2.96,
    density: 3.122,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
    description: 'Bromine is the only liquid nonmetal element at room temperature.',
  },
  {
    number: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicMass: 83.798,
    category: 'noble gas',
    block: 'p',
    group: 18,
    period: 4,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    density: 0.003733,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    description: 'Krypton is a noble gas that is colorless, odorless, and tasteless.',
  },
  {
    number: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    atomicMass: 85.4678,
    category: 'alkali metal',
    block: 's',
    group: 1,
    period: 5,
    electronConfiguration: '[Kr] 5s¹',
    electronegativity: 0.82,
    density: 1.532,
    meltingPoint: 312.46,
    boilingPoint: 961,
    description: 'Rubidium is a very soft, silvery-white metal that can be liquid at room temperature.',
  },
  {
    number: 38,
    symbol: 'Sr',
    name: 'Strontium',
    atomicMass: 87.62,
    category: 'alkaline earth metal',
    block: 's',
    group: 2,
    period: 5,
    electronConfiguration: '[Kr] 5s²',
    electronegativity: 0.95,
    density: 2.64,
    meltingPoint: 1050,
    boilingPoint: 1655,
    description: 'Strontium is a soft silver-white yellowish metallic element that is highly reactive chemically.',
  },
  {
    number: 39,
    symbol: 'Y',
    name: 'Yttrium',
    atomicMass: 88.90584,
    category: 'transition metal',
    block: 'd',
    group: 3,
    period: 5,
    electronConfiguration: '[Kr] 4d¹ 5s²',
    electronegativity: 1.22,
    density: 4.469,
    meltingPoint: 1799,
    boilingPoint: 3609,
    description: 'Yttrium is a silvery-metallic transition metal chemically similar to the lanthanides.',
  },
  {
    number: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    atomicMass: 91.224,
    category: 'transition metal',
    block: 'd',
    group: 4,
    period: 5,
    electronConfiguration: '[Kr] 4d² 5s²',
    electronegativity: 1.33,
    density: 6.506,
    meltingPoint: 2128,
    boilingPoint: 4682,
    description: 'Zirconium is a lustrous, grayish-white, strong transition metal resembling titanium.',
  },
  {
    number: 41,
    symbol: 'Nb',
    name: 'Niobium',
    atomicMass: 92.90637,
    category: 'transition metal',
    block: 'd',
    group: 5,
    period: 5,
    electronConfiguration: '[Kr] 4d⁴ 5s¹',
    electronegativity: 1.6,
    density: 8.57,
    meltingPoint: 2750,
    boilingPoint: 5017,
    description: 'Niobium is a shiny, white, soft, and ductile transition metal.',
  },
  {
    number: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    atomicMass: 95.95,
    category: 'transition metal',
    block: 'd',
    group: 6,
    period: 5,
    electronConfiguration: '[Kr] 4d⁵ 5s¹',
    electronegativity: 2.16,
    density: 10.22,
    meltingPoint: 2896,
    boilingPoint: 4912,
    description: 'Molybdenum is a silvery metal with a gray cast, has the sixth-highest melting point of any element.',
  },
  {
    number: 43,
    symbol: 'Tc',
    name: 'Technetium',
    atomicMass: 98,
    category: 'transition metal',
    block: 'd',
    group: 7,
    period: 5,
    electronConfiguration: '[Kr] 4d⁵ 5s²',
    electronegativity: 1.9,
    density: 11.5,
    meltingPoint: 2430,
    boilingPoint: 4538,
    description: 'Technetium is the lightest element whose isotopes are all radioactive.',
  },
  {
    number: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    atomicMass: 101.07,
    category: 'transition metal',
    block: 'd',
    group: 8,
    period: 5,
    electronConfiguration: '[Kr] 4d⁷ 5s¹',
    electronegativity: 2.2,
    density: 12.37,
    meltingPoint: 2607,
    boilingPoint: 4423,
    description: 'Ruthenium is a rare transition metal belonging to the platinum group.',
  },
  {
    number: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    atomicMass: 102.90550,
    category: 'transition metal',
    block: 'd',
    group: 9,
    period: 5,
    electronConfiguration: '[Kr] 4d⁸ 5s¹',
    electronegativity: 2.28,
    density: 12.41,
    meltingPoint: 2237,
    boilingPoint: 3968,
    description: 'Rhodium is a noble, silver-white metallic element that is highly resistant to corrosion.',
  },
  {
    number: 46,
    symbol: 'Pd',
    name: 'Palladium',
    atomicMass: 106.42,
    category: 'transition metal',
    block: 'd',
    group: 10,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰',
    electronegativity: 2.20,
    density: 12.02,
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    description: 'Palladium is a rare and lustrous silvery-white metal used in catalytic converters.',
  },
  {
    number: 47,
    symbol: 'Ag',
    name: 'Silver',
    atomicMass: 107.8682,
    category: 'transition metal',
    block: 'd',
    group: 11,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s¹',
    electronegativity: 1.93,
    density: 10.49,
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    description: 'Silver is a soft, lustrous transition metal known for its highest electrical and thermal conductivity of any element.',
  },
  {
    number: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    atomicMass: 112.414,
    category: 'transition metal',
    block: 'd',
    group: 12,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s²',
    electronegativity: 1.69,
    density: 8.65,
    meltingPoint: 594.22,
    boilingPoint: 1040,
    description: 'Cadmium is a soft, silvery-white metal that is chemically similar to zinc and mercury.',
  },
  {
    number: 49,
    symbol: 'In',
    name: 'Indium',
    atomicMass: 114.818,
    category: 'post-transition metal',
    block: 'p',
    group: 13,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p¹',
    electronegativity: 1.78,
    density: 7.31,
    meltingPoint: 429.75,
    boilingPoint: 2345,
    description: 'Indium is a post-transition metal that is very soft and silvery-white in color.',
  },
  {
    number: 50,
    symbol: 'Sn',
    name: 'Tin',
    atomicMass: 118.710,
    category: 'post-transition metal',
    block: 'p',
    group: 14,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p²',
    electronegativity: 1.96,
    density: 7.287,
    meltingPoint: 505.08,
    boilingPoint: 2875,
    description: 'Tin is a post-transition metal that is malleable and resistant to corrosion.',
  },
  {
    number: 51,
    symbol: 'Sb',
    name: 'Antimony',
    atomicMass: 121.760,
    category: 'metalloid',
    block: 'p',
    group: 15,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p³',
    electronegativity: 2.05,
    density: 6.685,
    meltingPoint: 903.78,
    boilingPoint: 1860,
    description: 'Antimony is a lustrous gray metalloid used in flame-proofing compounds and alloys.',
  },
  {
    number: 52,
    symbol: 'Te',
    name: 'Tellurium',
    atomicMass: 127.60,
    category: 'metalloid',
    block: 'p',
    group: 16,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁴',
    electronegativity: 2.1,
    density: 6.232,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    description: 'Tellurium is a silvery-white metalloid that exhibits semiconducting properties.',
  },
  {
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    atomicMass: 126.90447,
    category: 'halogen',
    block: 'p',
    group: 17,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁵',
    electronegativity: 2.66,
    density: 4.93,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    description: 'Iodine is a bluish-black, lustrous solid that sublimes easily into a violet gas.',
  },
  {
    number: 54,
    symbol: 'Xe',
    name: 'Xenon',
    atomicMass: 131.293,
    category: 'noble gas',
    block: 'p',
    group: 18,
    period: 5,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁶',
    density: 0.005887,
    meltingPoint: 161.4,
    boilingPoint: 165.03,
    description: 'Xenon is a colorless, dense, noble gas found in trace amounts in Earth\'s atmosphere.',
  },
  {
    number: 55,
    symbol: 'Cs',
    name: 'Cesium',
    atomicMass: 132.90545196,
    category: 'alkali metal',
    block: 's',
    group: 1,
    period: 6,
    electronConfiguration: '[Xe] 6s¹',
    electronegativity: 0.79,
    density: 1.873,
    meltingPoint: 301.59,
    boilingPoint: 944,
    discoveredBy: 'Robert Bunsen and Gustav Kirchhoff',
    yearDiscovered: 1860,
    description: 'Cesium is a soft, silvery-gold alkali metal that is highly reactive and soft.',
  },
  {
    number: 56,
    symbol: 'Ba',
    name: 'Barium',
    atomicMass: 137.327,
    category: 'alkaline earth metal',
    block: 's',
    group: 2,
    period: 6,
    electronConfiguration: '[Xe] 6s²',
    electronegativity: 0.89,
    density: 3.51,
    meltingPoint: 1000,
    boilingPoint: 2112,
    discoveredBy: 'Humphrey Davy',
    yearDiscovered: 1808,
    description: 'Barium is a soft, silvery-white alkaline earth metal that is highly reactive chemically.',
  },
  {
    number: 57,
    symbol: 'La',
    name: 'Lanthanum',
    atomicMass: 138.90547,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 5d¹ 6s²',
    electronegativity: 1.1,
    density: 6.145,
    meltingPoint: 1193,
    boilingPoint: 3737,
    description: 'Lanthanum is a soft, ductile, and silvery-white metal that belongs to the lanthanide series.',
  },
  {
    number: 58,
    symbol: 'Ce',
    name: 'Cerium',
    atomicMass: 140.116,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f¹ 5d¹ 6s²',
    electronegativity: 1.12,
    density: 6.77,
    meltingPoint: 1068,
    boilingPoint: 3716,
    description: 'Cerium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    atomicMass: 140.90765,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f³ 6s²',
    electronegativity: 1.13,
    density: 6.773,
    meltingPoint: 1204,
    boilingPoint: 3793,
    description: 'Praseodymium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    atomicMass: 144.242,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f⁴ 6s²',
    electronegativity: 1.14,
    density: 7.007,
    meltingPoint: 1387,
    boilingPoint: 3347,
    description: 'Neodymium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 61,
    symbol: 'Pm',
    name: 'Promethium',
    atomicMass: 145,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f⁵ 6s²',
    electronegativity: 1.13,
    density: 7.26,
    meltingPoint: 1315,
    boilingPoint: 3200,
    description: 'Promethium is a synthetic element and the only radioactive lanthanoid.',
  },
  {
    number: 62,
    symbol: 'Sm',
    name: 'Samarium',
    atomicMass: 150.36,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f⁶ 6s²',
    electronegativity: 1.17,
    density: 7.52,
    meltingPoint: 1345,
    boilingPoint: 2173,
    description: 'Samarium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 63,
    symbol: 'Eu',
    name: 'Europium',
    atomicMass: 151.964,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f⁷ 6s²',
    electronegativity: 1.2,
    density: 5.24,
    meltingPoint: 1299,
    boilingPoint: 2233,
    description: 'Europium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    atomicMass: 157.25,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f⁷ 5d¹ 6s²',
    electronegativity: 1.2,
    density: 7.895,
    meltingPoint: 1585,
    boilingPoint: 3546,
    description: 'Gadolinium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 65,
    symbol: 'Tb',
    name: 'Terbium',
    atomicMass: 158.92535,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f⁹ 6s²',
    electronegativity: 1.22,
    density: 8.23,
    meltingPoint: 1629,
    boilingPoint: 3503,
    description: 'Terbium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    atomicMass: 162.500,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁰ 6s²',
    electronegativity: 1.23,
    density: 8.55,
    meltingPoint: 1685,
    boilingPoint: 3403,
    description: 'Dysprosium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 67,
    symbol: 'Ho',
    name: 'Holmium',
    atomicMass: 164.93032,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f¹¹ 6s²',
    electronegativity: 1.24,
    density: 8.795,
    meltingPoint: 1734,
    boilingPoint: 3508,
    description: 'Holmium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 68,
    symbol: 'Er',
    name: 'Erbium',
    atomicMass: 167.259,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f¹² 6s²',
    electronegativity: 1.24,
    density: 9.066,
    meltingPoint: 1728,
    boilingPoint: 3593,
    description: 'Erbium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 69,
    symbol: 'Tm',
    name: 'Thulium',
    atomicMass: 168.93421,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f¹³ 6s²',
    electronegativity: 1.25,
    density: 9.32,
    meltingPoint: 1818,
    boilingPoint: 3503,
    description: 'Thulium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    atomicMass: 173.04,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 6s²',
    electronegativity: 1.1,
    density: 6.90,
    meltingPoint: 1297,
    boilingPoint: 3593,
    description: 'Ytterbium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    atomicMass: 174.967,
    category: 'lanthanoid',
    block: 'f',
    group: 3,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹ 6s²',
    electronegativity: 1.27,
    density: 9.841,
    meltingPoint: 1936,
    boilingPoint: 3675,
    description: 'Lutetium is a soft, ductile, and silvery-white lanthanoid element.',
  },
  {
    number: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    atomicMass: 178.49,
    category: 'transition metal',
    block: 'd',
    group: 4,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d² 6s²',
    electronegativity: 1.3,
    density: 13.31,
    meltingPoint: 2506,
    boilingPoint: 4876,
    description: 'Hafnium is a hard, gray, lustrous transition metal.',
  },
  {
    number: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    atomicMass: 180.94788,
    category: 'transition metal',
    block: 'd',
    group: 5,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d³ 6s²',
    electronegativity: 1.5,
    density: 16.65,
    meltingPoint: 3290,
    boilingPoint: 5731,
    description: 'Tantalum is a hard, gray, lustrous transition metal.',
  },
  {
    number: 74,
    symbol: 'W',
    name: 'Tungsten',
    atomicMass: 183.84,
    category: 'transition metal',
    block: 'd',
    group: 6,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    electronegativity: 1.7,
    density: 19.25,
    meltingPoint: 3695,
    boilingPoint: 5828,
    description: 'Tungsten is a hard, brittle, grayish-white transition metal.',
  },
  {
    number: 75,
    symbol: 'Re',
    name: 'Rhenium',
    atomicMass: 186.207,
    category: 'transition metal',
    block: 'd',
    group: 7,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    electronegativity: 1.9,
    density: 21.02,
    meltingPoint: 3459,
    boilingPoint: 5869,
    description: 'Rhenium is a hard, brittle, silvery-white transition metal.',
  },
  {
    number: 76,
    symbol: 'Os',
    name: 'Osmium',
    atomicMass: 190.23,
    category: 'transition metal',
    block: 'd',
    group: 8,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    electronegativity: 2.2,
    density: 22.58,
    meltingPoint: 3306,
    boilingPoint: 5285,
    description: 'Osmium is a hard, brittle, bluish-white transition metal.',
  },
  {
    number: 77,
    symbol: 'Ir',
    name: 'Iridium',
    atomicMass: 192.217,
    category: 'transition metal',
    block: 'd',
    group: 9,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    electronegativity: 2.2,
    density: 22.56,
    meltingPoint: 2719,
    boilingPoint: 4701,
    description: 'Iridium is a hard, brittle, bluish-white transition metal.',
  },
  {
    number: 78,
    symbol: 'Pt',
    name: 'Platinum',
    atomicMass: 195.084,
    category: 'transition metal',
    block: 'd',
    group: 10,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    electronegativity: 2.28,
    density: 21.45,
    meltingPoint: 2041,
    boilingPoint: 4098,
    description: 'Platinum is a hard, ductile, and malleable transition metal.',
  },
  {
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    atomicMass: 196.966569,
    category: 'transition metal',
    block: 'd',
    group: 11,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    electronegativity: 2.54,
    density: 19.32,
    meltingPoint: 1337.33,
    boilingPoint: 3243,
    description: 'Gold is a soft, yellow, precious metal.',
  },
  {
    number: 80,
    symbol: 'Hg',
    name: 'Mercury',
    atomicMass: 200.59,
    category: 'post-transition metal',
    block: 'd',
    group: 12,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    electronegativity: 2.00,
    density: 13.534,
    meltingPoint: 234.32,
    boilingPoint: 356.93,
    description: 'Mercury is a soft, liquid, precious metal.',
  },
  {
    number: 81,
    symbol: 'Tl',
    name: 'Thallium',
    atomicMass: 204.3833,
    category: 'post-transition metal',
    block: 'p',
    group: 13,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    electronegativity: 1.62,
    density: 11.85,
    meltingPoint: 577,
    boilingPoint: 1746,
    description: 'Thallium is a soft, silvery, toxic post-transition metal.',
  },
  {
    number: 82,
    symbol: 'Pb',
    name: 'Lead',
    atomicMass: 207.2,
    category: 'post-transition metal',
    block: 'p',
    group: 14,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    electronegativity: 1.82,
    density: 11.34,
    meltingPoint: 600.35,
    boilingPoint: 2270,
    description: 'Lead is a soft, malleable, and ductile post-transition metal.',
  },
  {
    number: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    atomicMass: 208.98040,
    category: 'post-transition metal',
    block: 'p',
    group: 15,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    electronegativity: 2.02,
    density: 9.78,
    meltingPoint: 544.55,
    boilingPoint: 1837,
    description: 'Bismuth is a brittle, gray, and toxic post-transition metal.',
  },
  {
    number: 84,
    symbol: 'Po',
    name: 'Polonium',
    atomicMass: 208.9824,
    category: 'metalloid',
    block: 'p',
    group: 16,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    electronegativity: 2.0,
    density: 9.196,
    meltingPoint: 527,
    boilingPoint: 1235,
    description: 'Polonium is a brittle, radioactive, and toxic metalloid.',
  },
  {
    number: 85,
    symbol: 'At',
    name: 'Astatine',
    atomicMass: 209.9871,
    category: 'metalloid',
    block: 'p',
    group: 17,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    electronegativity: 2.2,
    density: 7.00,
    meltingPoint: 575,
    boilingPoint: 610,
    description: 'Astatine is a brittle, radioactive, and toxic metalloid.',
  },
  {
    number: 86,
    symbol: 'Rn',
    name: 'Radon',
    atomicMass: 222.0176,
    category: 'noble gas',
    block: 'p',
    group: 18,
    period: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    density: 0.00973,
    meltingPoint: 202,
    boilingPoint: 211.4,
    description: 'Radon is a colorless, odorless, and radioactive noble gas.',
  },
  {
    number: 87,
    symbol: 'Fr',
    name: 'Francium',
    atomicMass: 223,
    category: 'alkali metal',
    block: 's',
    group: 1,
    period: 7,
    electronConfiguration: '[Rn] 7s¹',
    electronegativity: 0.7,
    density: 0.86,
    meltingPoint: 27,
    boilingPoint: 677,
    description: 'Francium is a soft, silvery-white, radioactive alkali metal.',
  },
  {
    number: 88,
    symbol: 'Ra',
    name: 'Radium',
    atomicMass: 226,
    category: 'alkaline earth metal',
    block: 's',
    group: 2,
    period: 7,
    electronConfiguration: '[Rn] 7s²',
    electronegativity: 0.9,
    density: 5.5,
    meltingPoint: 973,
    boilingPoint: 2010,
    description: 'Radium is a soft, silvery-white, radioactive alkaline earth metal.',
  },
  {
    number: 89,
    symbol: 'Ac',
    name: 'Actinium',
    atomicMass: 227,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 6d¹ 7s²',
    electronegativity: 1.1,
    density: 10.07,
    meltingPoint: 1323,
    boilingPoint: 3471,
    description: 'Actinium is a radioactive chemical element that glows blue in the dark.',
  },
  {
    number: 90,
    symbol: 'Th',
    name: 'Thorium',
    atomicMass: 232.03806,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 6d² 7s²',
    electronegativity: 1.3,
    density: 11.72,
    meltingPoint: 2023,
    boilingPoint: 5061,
    description: 'Thorium is a radioactive actinoid metal.',
  },
  {
    number: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    atomicMass: 231.03588,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f² 6d¹ 7s²',
    electronegativity: 1.5,
    density: 15.37,
    meltingPoint: 1845,
    boilingPoint: 4300,
    description: 'Protactinium is a radioactive actinoid metal.',
  },
  {
    number: 92,
    symbol: 'U',
    name: 'Uranium',
    atomicMass: 238.02891,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f³ 6d¹ 7s²',
    electronegativity: 1.38,
    density: 19.1,
    meltingPoint: 1405,
    boilingPoint: 4404,
    description: 'Uranium is a radioactive actinoid metal.',
  },
  {
    number: 93,
    symbol: 'Np',
    name: 'Neptunium',
    atomicMass: 237,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f⁴ 6d¹ 7s²',
    electronegativity: 1.36,
    density: 20.45,
    meltingPoint: 913,
    boilingPoint: 4175,
    description: 'Neptunium is a synthetic actinoid metal.',
  },
  {
    number: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    atomicMass: 244,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f⁶ 7s²',
    electronegativity: 1.28,
    density: 19.816,
    meltingPoint: 913,
    boilingPoint: 3500,
    description: 'Plutonium is a synthetic actinoid metal.',
  },
  {
    number: 95,
    symbol: 'Am',
    name: 'Americium',
    atomicMass: 243,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f⁷ 7s²',
    electronegativity: 1.3,
    density: 13.67,
    meltingPoint: 1225,
    boilingPoint: 3140,
    description: 'Americium is a synthetic actinoid metal.',
  },
  {
    number: 96,
    symbol: 'Cm',
    name: 'Curium',
    atomicMass: 247,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f⁷ 6d¹ 7s²',
    electronegativity: 1.3,
    density: 13.51,
    meltingPoint: 1613,
    boilingPoint: 3383,
    description: 'Curium is a synthetic actinoid metal that glows with an intense radioactive blue-violet light.',
  },
  {
    number: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    atomicMass: 247,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f⁹ 7s²',
    electronegativity: 1.3,
    density: 14.78,
    meltingPoint: 1259,
    boilingPoint: 2900,
    description: 'Berkelium is a synthetic actinoid metal.',
  },
  {
    number: 98,
    symbol: 'Cf',
    name: 'Californium',
    atomicMass: 251,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁰ 7s²',
    electronegativity: 1.3,
    density: 15.1,
    meltingPoint: 1173,
    boilingPoint: 1743,
    description: 'Californium is a synthetic actinoid metal.',
  },
  {
    number: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    atomicMass: 252,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f¹¹ 7s²',
    electronegativity: 1.3,
    density: 8.84,
    meltingPoint: 1133,
    boilingPoint: 1269,
    description: 'Einsteinium is a synthetic actinoid metal.',
  },
  {
    number: 100,
    symbol: 'Fm',
    name: 'Fermium',
    atomicMass: 257,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f¹² 7s²',
    electronegativity: 1.3,
    density: undefined,
    meltingPoint: 1800,
    boilingPoint: undefined,
    description: 'Fermium is a synthetic actinoid metal.',
  },
  {
    number: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    atomicMass: 258,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f¹³ 7s²',
    electronegativity: 1.3,
    density: undefined,
    meltingPoint: 1100,
    boilingPoint: undefined,
    description: 'Mendelevium is a synthetic actinoid metal.',
  },
  {
    number: 102,
    symbol: 'No',
    name: 'Nobelium',
    atomicMass: 259,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 7s²',
    electronegativity: 1.3,
    density: undefined,
    meltingPoint: 1100,
    boilingPoint: undefined,
    description: 'Nobelium is a synthetic actinoid metal.',
  },
  {
    number: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    atomicMass: 266,
    category: 'actinoid',
    block: 'f',
    group: 3,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 7s² 7p¹',
    electronegativity: 1.3,
    density: undefined,
    meltingPoint: 1900,
    boilingPoint: undefined,
    description: 'Lawrencium is a synthetic actinoid metal.',
  },
  {
    number: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    atomicMass: 267,
    category: 'transition metal',
    block: 'd',
    group: 4,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d² 7s²',
    electronegativity: undefined,
    density: 23.2,
    meltingPoint: 2400,
    boilingPoint: 5800,
    description: 'Rutherfordium is a synthetic transition metal.',
  },
  {
    number: 105,
    symbol: 'Db',
    name: 'Dubnium',
    atomicMass: 268,
    category: 'transition metal',
    block: 'd',
    group: 5,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d³ 7s²',
    electronegativity: undefined,
    density: 29.3,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Dubnium is a synthetic transition metal.',
  },
  {
    number: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    atomicMass: 269,
    category: 'transition metal',
    block: 'd',
    group: 6,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁴ 7s²',
    electronegativity: undefined,
    density: 35.0,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Seaborgium is a synthetic transition metal.',
  },
  {
    number: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    atomicMass: 270,
    category: 'transition metal',
    block: 'd',
    group: 7,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁵ 7s²',
    electronegativity: undefined,
    density: 37.1,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Bohrium is a synthetic transition metal.',
  },
  {
    number: 108,
    symbol: 'Hs',
    name: 'Hassium',
    atomicMass: 269,
    category: 'transition metal',
    block: 'd',
    group: 8,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁶ 7s²',
    electronegativity: undefined,
    density: 40.7,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Hassium is a synthetic transition metal.',
  },
  {
    number: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    atomicMass: 278,
    category: 'transition metal',
    block: 'd',
    group: 9,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁷ 7s²',
    electronegativity: undefined,
    density: 37.4,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Meitnerium is a synthetic transition metal.',
  },
  {
    number: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    atomicMass: 281,
    category: 'transition metal',
    block: 'd',
    group: 10,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁸ 7s²',
    electronegativity: undefined,
    density: 34.8,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Darmstadtium is a synthetic transition metal.',
  },
  {
    number: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    atomicMass: 282,
    category: 'transition metal',
    block: 'd',
    group: 11,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁹ 7s²',
    electronegativity: undefined,
    density: 28.7,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Roentgenium is a synthetic transition metal.',
  },
  {
    number: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    atomicMass: 285,
    category: 'transition metal',
    block: 'd',
    group: 12,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',
    electronegativity: undefined,
    density: 23.7,
    meltingPoint: undefined,
    boilingPoint: undefined,
    description: 'Copernicium is a synthetic transition metal.',
  },
  {
    number: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    atomicMass: 286,
    category: 'post-transition metal',
    block: 'p',
    group: 13,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
    electronegativity: undefined,
    density: 16,
    meltingPoint: 700,
    boilingPoint: 1400,
    description: 'Nihonium is a synthetic post-transition metal.',
  },
  {
    number: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    atomicMass: 289,
    category: 'post-transition metal',
    block: 'p',
    group: 14,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
    electronegativity: undefined,
    density: 14,
    meltingPoint: 340,
    boilingPoint: 420,
    description: 'Flerovium is a synthetic post-transition metal.',
  },
  {
    number: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    atomicMass: 290,
    category: 'post-transition metal',
    block: 'p',
    group: 15,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
    electronegativity: undefined,
    density: 13.5,
    meltingPoint: 670,
    boilingPoint: 1400,
    description: 'Moscovium is a synthetic post-transition metal.',
  },
  {
    number: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    atomicMass: 293,
    category: 'post-transition metal',
    block: 'p',
    group: 16,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
    electronegativity: undefined,
    density: 12.9,
    meltingPoint: 709,
    boilingPoint: 1085,
    description: 'Livermorium is a synthetic post-transition metal.',
  },
  {
    number: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    atomicMass: 294,
    category: 'halogen',
    block: 'p',
    group: 17,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
    electronegativity: undefined,
    density: 7.2,
    meltingPoint: 723,
    boilingPoint: 883,
    description: 'Tennessine is a synthetic halogen.',
  },
  {
    number: 118,
    symbol: 'Og',
    name: 'Oganesson',
    atomicMass: 294,
    category: 'noble gas',
    block: 'p',
    group: 18,
    period: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
    electronegativity: undefined,
    density: 5,
    meltingPoint: 325,
    boilingPoint: 350,
    description: 'Oganesson is a synthetic noble gas.',
  }
]; 